name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'IlonaShishov'

    steps:
    - name: Checkout sources
      uses: actions/checkout@v3

    - name: Install node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        registry-url: 'https://npm.pkg.github.com'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create .npmrc
      run: |
        echo "@RHEcosystemAppEng:registry=https://npm.pkg.github.com" >> ~/.npmrc

    - name: Install Dependencies
      run: npm ci

    - name: Lint Code
      run: npm run lint

    - name: Run Unit Tests
      run: npm test -- --coverage

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}