# https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md
name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .npmrc
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PKG_TOKEN }}" > .npmrc
          echo "@RHEcosystemAppEng:registry=https://npm.pkg.github.com" >> .npmrc
          ls -al
          cat .npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          token: ${{ secrets.PKG_TOKEN }}
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
        run: npx semantic-release
